/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.KeyStroke;

/**
 *
 * @author Feylin
 */
public class About extends JDialog
{
    private static About instance = null;
    String osArch = System.getProperty("os.arch");
    String osVersion = System.getProperty("os.version");
    String osName = System.getProperty("os.name");
    String javaVendor = System.getProperty("java.vendor");
    String javaVersion = System.getProperty("java.version");
    String userName = System.getProperty("user.name");
    String userHome = System.getProperty("user.home");

    /**
     * Creates new form About
     */
    public About()
    {
        setModal(true);
        initComponents();
        setLocationRelativeTo(null);
        closeListener();
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/icons/tennis_ball.png")).getImage());
        txtJava.setText(javaVersion +"; " +javaVendor);
        txtSystem.setText(osName +" version " +osVersion +" running on " +osArch);
        txtUserName.setText(userName);
        txtUserHome.setText(userHome);
    }
    
    public static About getInstance()
    {
        if (instance == null)
        {
            instance = new About();
        }
        return instance;
    }
    
    private void closeListener()
    {
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(
                KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "close");
        getRootPane().getActionMap().put("close", new AbstractAction()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblJava = new javax.swing.JTextField();
        txtProduct = new javax.swing.JTextField();
        txtVersion = new javax.swing.JTextField();
        jspAbout = new javax.swing.JScrollPane();
        txtAbout = new javax.swing.JTextPane();
        btnClose = new javax.swing.JButton();
        lblEASV = new javax.swing.JLabel();
        txtJava = new javax.swing.JTextField();
        lblSystem = new javax.swing.JTextField();
        txtSystem = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        txtUserHome = new javax.swing.JTextField();
        lblUserName = new javax.swing.JTextField();
        lblUserHome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJava.setEditable(false);
        lblJava.setBackground(new java.awt.Color(255, 255, 255));
        lblJava.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblJava.setText("Java: ");
        lblJava.setBorder(null);
        lblJava.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                lblJavaActionPerformed(evt);
            }
        });

        txtProduct.setEditable(false);
        txtProduct.setBackground(new java.awt.Color(255, 255, 255));
        txtProduct.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtProduct.setText("Product Version: ");
        txtProduct.setBorder(null);

        txtVersion.setEditable(false);
        txtVersion.setBackground(new java.awt.Color(255, 255, 255));
        txtVersion.setText("Tie Break 1.01a (Build 120409002013)");
        txtVersion.setBorder(null);
        txtVersion.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtVersionActionPerformed(evt);
            }
        });

        jspAbout.setBorder(null);

        txtAbout.setEditable(false);
        txtAbout.setBackground(new java.awt.Color(240, 240, 240));
        txtAbout.setText("This program was developed by\nRashid Abdel-Majid, Mak Jakubovic, Kim Reenberg and Klaus Andresen");
        jspAbout.setViewportView(txtAbout);

        btnClose.setText("Close");
        btnClose.setToolTipText("Closes the window");
        btnClose.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCloseActionPerformed(evt);
            }
        });

        lblEASV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Logo.JPG"))); // NOI18N

        txtJava.setEditable(false);
        txtJava.setBackground(new java.awt.Color(255, 255, 255));
        txtJava.setBorder(null);
        txtJava.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtJavaActionPerformed(evt);
            }
        });

        lblSystem.setEditable(false);
        lblSystem.setBackground(new java.awt.Color(255, 255, 255));
        lblSystem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSystem.setText("System: ");
        lblSystem.setBorder(null);
        lblSystem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                lblSystemActionPerformed(evt);
            }
        });

        txtSystem.setEditable(false);
        txtSystem.setBackground(new java.awt.Color(255, 255, 255));
        txtSystem.setBorder(null);
        txtSystem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtSystemActionPerformed(evt);
            }
        });

        txtUserName.setEditable(false);
        txtUserName.setBackground(new java.awt.Color(255, 255, 255));
        txtUserName.setBorder(null);
        txtUserName.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtUserNameActionPerformed(evt);
            }
        });

        txtUserHome.setEditable(false);
        txtUserHome.setBackground(new java.awt.Color(255, 255, 255));
        txtUserHome.setBorder(null);
        txtUserHome.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtUserHomeActionPerformed(evt);
            }
        });

        lblUserName.setEditable(false);
        lblUserName.setBackground(new java.awt.Color(255, 255, 255));
        lblUserName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUserName.setText("User Name: ");
        lblUserName.setBorder(null);
        lblUserName.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                lblUserNameActionPerformed(evt);
            }
        });

        lblUserHome.setEditable(false);
        lblUserHome.setBackground(new java.awt.Color(255, 255, 255));
        lblUserHome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUserHome.setText("User Home: ");
        lblUserHome.setBorder(null);
        lblUserHome.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                lblUserHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblUserHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtUserHome))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblJava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtJava))
                    .addComponent(jspAbout, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtVersion))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSystem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtSystem))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtUserName)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(btnClose))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(lblEASV)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEASV)
                .addGap(18, 18, 18)
                .addComponent(jspAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSystem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSystem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblJavaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_lblJavaActionPerformed
    {//GEN-HEADEREND:event_lblJavaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblJavaActionPerformed

    private void txtVersionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtVersionActionPerformed
    {//GEN-HEADEREND:event_txtVersionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVersionActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCloseActionPerformed
    {//GEN-HEADEREND:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtJavaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtJavaActionPerformed
    {//GEN-HEADEREND:event_txtJavaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJavaActionPerformed

    private void lblSystemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_lblSystemActionPerformed
    {//GEN-HEADEREND:event_lblSystemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSystemActionPerformed

    private void txtSystemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtSystemActionPerformed
    {//GEN-HEADEREND:event_txtSystemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSystemActionPerformed

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtUserNameActionPerformed
    {//GEN-HEADEREND:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void txtUserHomeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtUserHomeActionPerformed
    {//GEN-HEADEREND:event_txtUserHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserHomeActionPerformed

    private void lblUserNameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_lblUserNameActionPerformed
    {//GEN-HEADEREND:event_lblUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUserNameActionPerformed

    private void lblUserHomeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_lblUserHomeActionPerformed
    {//GEN-HEADEREND:event_lblUserHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUserHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new About().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JScrollPane jspAbout;
    private javax.swing.JLabel lblEASV;
    private javax.swing.JTextField lblJava;
    private javax.swing.JTextField lblSystem;
    private javax.swing.JTextField lblUserHome;
    private javax.swing.JTextField lblUserName;
    private javax.swing.JTextPane txtAbout;
    private javax.swing.JTextField txtJava;
    private javax.swing.JTextField txtProduct;
    private javax.swing.JTextField txtSystem;
    private javax.swing.JTextField txtUserHome;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtVersion;
    // End of variables declaration//GEN-END:variables
}
