/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BE.Operator;
import BE.Order;
import BLL.OperatorManager;
import BLL.OrderManager;
import BLL.SleeveLogManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel, Klaus, Mak, Rashid
 */

public class SleeveInfo extends JDialog
{
    private Order order;
    private OrderManager omgr = null;
    private Operator operator;
    private OperatorManager opmgr = null;
    private SleeveLogManager slmgr = null;

    /**
     * Creates new form SleeveInfo
     */
    public SleeveInfo(Order o, Operator op)
    {
        setModal(true);
        operator = op;
        try
        {
            omgr = OrderManager.getInstance();
            opmgr = OperatorManager.getInstance();
            slmgr = SleeveLogManager.getInstance();
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
        }
        order = o;
        initComponents();
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/icons/belman.png")).getImage());
        numbersOnlyKeyListener();
        setLocationByPlatform(true);

        txtTotal.setText(String.valueOf(o.getQuantity()));
    }

    private void numbersOnlyKeyListener()
    {
        txtHasCut.addKeyListener(new gui.NumbersOnlyKeyListener());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnOk = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtHasCut = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Belman Manager");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnOkActionPerformed(evt);
            }
        });

        jLabel1.setText("Sleeves Made:");

        jLabel2.setText("Of");

        txtTotal.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHasCut, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtHasCut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOk)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        int cut = Integer.parseInt(txtHasCut.getText()) + order.getConductedQuantity();

        if (cut <= order.getQuantity())
        {
            order.setConductedQuantity(cut);
            try
            {
                omgr.update(order);
                slmgr.addLog(order.getSleeve().getId(), operator, cut, 0);
                dispose();
            }
            catch (SQLException ex)
            {
               ex.printStackTrace();
            } 
        }
//        if (cut == order.getQuantity())
//        {
//            order.setConductedQuantity(cut);
//            String status = "Finished";
//            order.setStatus(status.toUpperCase());
//            try
//            {
//                omgr.update(order);
//                slmgr.addLog(order.getSleeve().getId(), operator, cut, 0);
//                dispose();
//            }
//            catch (SQLException ex)
//            {
//               ex.printStackTrace();
//            }
//        }
        else
        {
            String message = "Error : You cant cut more than the total quantity ";
            int reply = JOptionPane.showConfirmDialog(null, message, getTitle(), JOptionPane.OK_CANCEL_OPTION);
            if (reply == JOptionPane.CANCEL_OPTION)
            {
                dispose();
            }

        }
    }//GEN-LAST:event_btnOkActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtHasCut;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
